#!/usr/bin/env ruby

require 'appiconset'
require 'json'
require 'optparse'
require 'fileutils'
require 'fastimage'
require 'date'


options = {}
option_parser = OptionParser.new
option_parser.version = Appiconset::VERSION
option_parser.on('-o', '--output <output>', '') { |v| options[:output] = v }
option_parser.banner="Usage: #{File.basename($0)} [options] <input>"
option_parser.on("-h", "--help", "Show this message") { puts option_parser; exit }

option_parser.parse!(ARGV)

if options.has_key?(:output)
  output = options[:output]
else
  output = Dir::home + "/appiconset-generated-" + DateTime.now.strftime("%Y%m%d%H%M%S") + "/"
end

if ARGV.length == 0 || !File.exist?(ARGV[0])
  STDERR.puts "no input file"
  exit
else
  input = ARGV[0]
end

image_size = FastImage.size(input)

platforms = [
  {
    name: "universal",
    contents: [
      {size: image_size[0] / 3, scale: 3, idiom: "universal"},
      {size: image_size[0] / 3, scale: 2, idiom: "universal"},
      {size: image_size[0] / 3, scale: 1, idiom: "universal"}
    ]
  },
  {
    name: "tv",
    contents: [
      {size: image_size[0] / 2, scale: 2, idiom: "tv"},
      {size: image_size[0] / 2, scale: 1, idiom: "tv"}
    ]
  },
  {
    name: "tv-top-shelf",
    contents: [
      {size: image_size[0] / 2, scale: 2, idiom: "tv"},
      {size: image_size[0] / 2, scale: 2, idiom: "tv-marketing"},
      {size: image_size[0] / 2, scale: 1, idiom: "tv"},
      {size: image_size[0] / 2, scale: 1, idiom: "tv-marketing"}
    ]
  }
]

platforms.each do |platform|
  output_dir = output + platform[:name] + "-xcode12.3"
  FileUtils.mkdir_p(output_dir) unless FileTest.exist?(output_dir)

  images = []

  platform[:contents].each do |content|
    name = "Icon-" + content[:idiom] + "-" + content[:size].to_s + "@" + content[:scale].to_s + "x.png"
    size = content[:size].to_s + "x" + content[:size].to_s
    real_size = content[:size].to_f * content[:scale].to_f
    scale = content[:scale].to_s + "x"
    command = sprintf("sips -Z %d %s --out %s/%s &> /dev/null ", real_size, input, output_dir, name)
    system(command)

    images << {
        size: size,
        idiom: content[:idiom],
        filename: name,
        scale: scale
    }
  end

  puts(output_dir)

  File.write(output_dir + "/Contents.json", JSON.pretty_generate({images: images, info: {version: 1, author: "xcode"}}))
end

# すべてのプラットフォームのアイコンを作成する

json_dir = Gem::Specification.find_by_path("appiconset").full_gem_path + "/lib/appiconset/*.json"

Dir.glob(json_dir).each do |path|
  json_data = open(path) do |content|
    JSON.load(content)
  end

  # プラットフォームごとのディレクトリ
  platform =  File.basename(path).gsub("-Contents.json", "")
  output_dir = output + platform
  FileUtils.mkdir_p(output_dir) unless FileTest.exist?(output_dir)

  puts(output_dir)

  json_data["images"].each do |image|
    size = image["size"].match(/(.*?)x/)[1].to_f
    scale = image["scale"].gsub("x", "").to_i
    # 実際のサイズ
    real_size = size * scale
    name = image["filename"]

    command = sprintf("sips -Z %d %s --out %s/%s &> /dev/null ", real_size, input, output_dir, name)
    system(command)
  end

  begin
    if json_data["info"]["author"] == "xcode"
      # Xcode用にファイルをコピーする
      FileUtils.cp(path, output_dir + "/Contents.json")
    end
  rescue
    # none
  end
end